version: 0.2

env:
    variables:
      ENV_VAR_NAME: "value"


phases:
  install:
    runtime-versions:
      java: openjdk17
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
